name: Deploy to EC2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verificar variáveis
        run: |
          echo "DOCKER_USERNAME está configurado: [${{ secrets.DOCKER_USERNAME }}]"
          echo "DOCKER_PASSWORD está configurado: [${{ secrets.DOCKER_PASSWORD }}]"
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t globo-clima/globo-clima .

      - name: Push image docker
        run: docker push globo-clima/globo-clima
