name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY}}
            HOSTNAME: ${{secrets.EC2_IP}}
            USER_NAME: ${{secrets.EC2_USER}}
        run:
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /globo-clima/globo-clima
            git pull origin main
            docker build -t globo-clima .
            docker stop globo-clima || true 
            docker rm globo-clima || true
            docker run -d -p 5000:5000 --name globo-clima globo-clima 
