name: teste

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Login Docker Hub
              run: docker login -u ${{secrets.EC2_USER}} -p ${{secrets.EC2_USER}}

            - name: Build docker image
              run: docker build -t globo-clima/globo-clima .

            - name: Push image docker
              run: docker push globo-clima/globo-clima
