name: Deploy to EC2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  call-workflow-passing-data:
    uses: globo-clima/.github/workflows/dotnet-desktop.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Login Docker Hub
        run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t globo-clima/globo-clima .

      - name: Push image docker
        run: docker push globo-clima/globo-clima
