name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }} 
          key: ${{ secrets.EC2_SSH_KEY }} 
          port: 22
          script: |
            cd /home/ubuntu/globo-clima
            git pull origin main
            docker build -t globo-clima .
            docker stop globo-clima || true 
            docker rm globo-clima || true
            docker run -d -p 5000:5000 --name globo-clima globo-clima 
